<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.0-dev setup script
 * Date: Thu, 03 May 2018 02:23:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: jws-simplyfit-mysql [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'jws-simplyfit-mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'user8M1';
$cfg['Servers'][$i]['password'] = '0Fj683Wq';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'jY9l&U28ze!4{7kR&h2"POJvC)?6Z>M';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>